name: super_editor_clipboard
description: "Rich text copy/paste extensions on super_editor."
version: 0.1.0
repository: https://github.com/superlistapp/super_editor/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  super_clipboard: ^0.9.1
  super_editor: 0.3.0-dev.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
